# coding: utf-8

"""
    Public Robot Events API

    An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using the query parameters `page` and `per_page`. Please not that dates should be formatted according to RFC3339.   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Generated by: https://openapi-generator.tech
"""

from rec.paths.events_id_awards.get import EventGetAwards
from rec.paths.events_id_divisions_div_finalist_rankings.get import EventGetDivisionFinalistRankings
from rec.paths.events_id_divisions_div_matches.get import EventGetDivisionMatches
from rec.paths.events_id_divisions_div_rankings.get import EventGetDivisionRankings
from rec.paths.events_id.get import EventGetEvent
from rec.paths.events.get import EventGetEvents
from rec.paths.events_id_skills.get import EventGetSkills
from rec.paths.events_id_teams.get import EventGetTeams


class EventApi(
    EventGetAwards,
    EventGetDivisionFinalistRankings,
    EventGetDivisionMatches,
    EventGetDivisionRankings,
    EventGetEvent,
    EventGetEvents,
    EventGetSkills,
    EventGetTeams,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
