# coding: utf-8

"""
    Public Robot Events API

    An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using the query parameters `page` and `per_page`. Please not that dates should be formatted according to RFC3339.   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class EventType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "tournament": "TOURNAMENT",
            "league": "LEAGUE",
            "workshop": "WORKSHOP",
            "virtual": "VIRTUAL",
        }
    
    @schemas.classproperty
    def TOURNAMENT(cls):
        return cls("tournament")
    
    @schemas.classproperty
    def LEAGUE(cls):
        return cls("league")
    
    @schemas.classproperty
    def WORKSHOP(cls):
        return cls("workshop")
    
    @schemas.classproperty
    def VIRTUAL(cls):
        return cls("virtual")
