# coding: utf-8

"""
    Public Robot Events API

    An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using the query parameters `page` and `per_page`. Please not that dates should be formatted according to RFC3339.   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.seasons_id_events.get import SeasonGetEvents
from openapi_client.paths.seasons_id.get import SeasonGetSeason
from openapi_client.paths.seasons.get import SeasonGetSeasons


class SeasonApi(
    SeasonGetEvents,
    SeasonGetSeason,
    SeasonGetSeasons,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
