# coding: utf-8

"""
    Public Robot Events API

    An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using the query parameters `page` and `per_page`. Please not that dates should be formatted according to RFC3339.   # noqa: E501

    The version of the OpenAPI document: 1.0.21
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.teams_id_awards.get import TeamGetAwards
from openapi_client.paths.teams_id_events.get import TeamGetEvents
from openapi_client.paths.teams_id_matches.get import TeamGetMatches
from openapi_client.paths.teams_id_rankings.get import TeamGetRankings
from openapi_client.paths.teams_id_skills.get import TeamGetSkills
from openapi_client.paths.teams_id.get import TeamGetTeam
from openapi_client.paths.teams.get import TeamGetTeams


class TeamApi(
    TeamGetAwards,
    TeamGetEvents,
    TeamGetMatches,
    TeamGetRankings,
    TeamGetSkills,
    TeamGetTeam,
    TeamGetTeams,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
